version: "3.8"

services:
  web:
    build:
      context: containers/dev
    ports:
      - ${APP_PORT}:${APP_PORT}
      - 2345:2345 # dlv debugger port
    volumes:
      - .:/projectdir
      - $GOPATH/pkg/mod:/go/pkg/mod
    env_file:
      - .env.local
    environment:
      PKG_CMD: ./cmd/web
      # GIN_MODE: "release"
    command: sh -c './wait-for.sh pgsql:${DB_PORT} -- ./entry.sh watch'
    depends_on:
      - pgsql

  pgsql:
    image: postgres:13.1
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}

volumes:
  pg_data:
